replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {
    nginx.ingress.kubernetes.io/rewrite-target: /
  }
  hosts:
    - host: localhost
      paths: [/nginx-template-new]
